"""Обновить клиентские коэффициенты: python -m scripts.export_preparation_heuristics."""

import json
from pathlib import Path

from app.preparation.estimation import HEURISTICS


def main() -> None:
    """Генерируемый файл позволяет собрать frontend без запущенного API."""
    destination = (
        Path(__file__).resolve().parents[2] / "frontend/src/api/generated/preparationHeuristics.ts"
    )
    destination.write_text(
        "// Generated by backend/scripts/export_preparation_heuristics.py; do not edit.\n"
        "export const preparationHeuristics = "
        + json.dumps(HEURISTICS, indent=2, ensure_ascii=False)
        + " as const;\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
