"""create stage 2 core

Revision ID: 34158831e181
Revises:
Create Date: 2026-08-06 17:47:08.889810
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "34158831e181"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_materials_sha256_lowercase_hex"),
        ),
        sa.CheckConstraint(
            "page_count IS NULL OR page_count > 0", name=op.f("ck_materials_page_count_positive")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_materials_size_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("sha256", name=op.f("uq_materials_sha256")),
        sa.UniqueConstraint("storage_path", name=op.f("uq_materials_storage_path")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "template_key",
            sa.Enum(
                "exam",
                "textbook",
                "free",
                name="template_key",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "workspace_variant",
            sa.Enum(
                "exam",
                "textbook",
                name="workspace_variant",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "archived",
                "completed",
                name="project_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("enabled_modules", sa.JSON(), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_projects_sort_order_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            "ix_projects_status_sort_order", ["status", "sort_order"], unique=False
        )

    op.create_table(
        "goal_passports",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "exam",
                "work",
                "interview",
                "interest",
                name="goal_purpose",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "scope",
            sa.Enum("whole", "goal", name="goal_scope", native_enum=False, create_constraint=True),
            nullable=True,
        ),
        sa.Column(
            "starting_level",
            sa.Enum(
                "beginner",
                "familiar",
                "refreshing",
                name="starting_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("current_knowledge", sa.String(), nullable=True),
        sa.Column(
            "target_outcome",
            sa.Enum(
                "awareness",
                "understanding",
                "application",
                "mastery",
                name="target_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("goal", sa.String(), nullable=True),
        sa.Column("success_criterion", sa.String(), nullable=True),
        sa.Column("important", sa.String(), nullable=True),
        sa.Column("excluded", sa.String(), nullable=True),
        sa.Column(
            "study_format",
            sa.Enum(
                "theory",
                "theory_and_practice",
                "practice",
                name="study_format",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("minutes_per_day", sa.Integer(), nullable=True),
        sa.Column("days_per_week", sa.Integer(), nullable=True),
        sa.Column("session_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "exam_format",
            sa.Enum(
                "questions",
                "questions_tasks",
                "tickets",
                "unknown",
                name="exam_format",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("expected_item_count", sa.Integer(), nullable=True),
        sa.Column("instructor_requirements", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "days_per_week IS NULL OR days_per_week BETWEEN 1 AND 7",
            name=op.f("ck_goal_passports_days_range"),
        ),
        sa.CheckConstraint(
            "expected_item_count IS NULL OR expected_item_count > 0",
            name=op.f("ck_goal_passports_expected_item_count_positive"),
        ),
        sa.CheckConstraint(
            "minutes_per_day IS NULL OR minutes_per_day > 0",
            name=op.f("ck_goal_passports_minutes_positive"),
        ),
        sa.CheckConstraint(
            "session_minutes IS NULL OR session_minutes > 0",
            name=op.f("ck_goal_passports_session_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_goal_passports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_goal_passports")),
    )
    op.create_table(
        "program_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "node_type",
            sa.Enum(
                "section",
                "topic",
                "subpoint",
                name="node_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "exam_kind",
            sa.Enum(
                "question",
                "task",
                "ticket",
                name="exam_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("section_purpose", sa.String(), nullable=True),
        sa.Column(
            "goal_role",
            sa.Enum(
                "target",
                "prerequisite",
                "related",
                name="goal_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "target_level",
            sa.Enum(
                "awareness",
                "understanding",
                "application",
                "mastery",
                name="node_target_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("is_in_current_program", sa.Boolean(), nullable=False),
        sa.Column("needs_material", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "origin_kind",
            sa.Enum(
                "manual",
                "import",
                "outline",
                "pass1",
                "catalog",
                "model",
                name="origin_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("origin_note", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_program_nodes_sort_order_nonnegative")),
        sa.ForeignKeyConstraint(
            ["project_id", "parent_id"],
            ["program_nodes.project_id", "program_nodes.id"],
            name=op.f("fk_program_nodes_project_id_program_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_program_nodes_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_nodes")),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_program_nodes_project_id")),
    )
    with op.batch_alter_table("program_nodes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_program_nodes_project_parent_order",
            ["project_id", "parent_id", "sort_order"],
            unique=False,
        )

    op.create_table(
        "project_materials",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_role",
            sa.Enum(
                "main",
                "additional",
                "reference",
                name="source_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("affects_program", sa.Boolean(), nullable=False),
        sa.Column("instruction", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_project_materials_priority_nonnegative")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_project_materials_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_materials_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "material_id", name=op.f("pk_project_materials")),
    )
    with op.batch_alter_table("project_materials", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_materials_project_priority", ["project_id", "priority"], unique=False
        )

    op.create_table(
        "wizard_drafts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("max_completed_step", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "current_step BETWEEN 1 AND 5", name=op.f("ck_wizard_drafts_current_step_range")
        ),
        sa.CheckConstraint(
            "max_completed_step BETWEEN 1 AND 5",
            name=op.f("ck_wizard_drafts_max_completed_step_range"),
        ),
        sa.CheckConstraint("revision >= 0", name=op.f("ck_wizard_drafts_revision_nonnegative")),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_wizard_drafts_schema_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_wizard_drafts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_wizard_drafts")),
    )
    with op.batch_alter_table("wizard_drafts", schema=None) as batch_op:
        batch_op.create_index("ix_wizard_drafts_updated_at", ["updated_at"], unique=False)

    op.create_table(
        "workspace_states",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("layout", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_workspace_states_schema_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workspace_states_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_workspace_states")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspace_states")
    with op.batch_alter_table("wizard_drafts", schema=None) as batch_op:
        batch_op.drop_index("ix_wizard_drafts_updated_at")

    op.drop_table("wizard_drafts")
    with op.batch_alter_table("project_materials", schema=None) as batch_op:
        batch_op.drop_index("ix_project_materials_project_priority")

    op.drop_table("project_materials")
    with op.batch_alter_table("program_nodes", schema=None) as batch_op:
        batch_op.drop_index("ix_program_nodes_project_parent_order")

    op.drop_table("program_nodes")
    op.drop_table("goal_passports")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_status_sort_order")

    op.drop_table("projects")
    op.drop_table("materials")
    # ### end Alembic commands ###
