"""Занятия и отменяемый календарь подготовки, без реконструкции старого времени."""

import sqlalchemy as sa
from alembic import op

revision = "20260904_prep_0033"
down_revision = "20260901_0031"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attempts", sa.Column("answer_mode", sa.String(), nullable=True))
    op.add_column("attempts", sa.Column("active_seconds", sa.Integer(), nullable=True))
    op.create_table(
        "preparation_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("base_revision", sa.Integer(), nullable=False),
        sa.Column("program_revision", sa.Integer(), nullable=False),
        sa.Column("settings_revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("applied_revision", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_preparation_drafts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preparation_drafts")),
    )
    op.create_index(
        op.f("ix_preparation_drafts_project_id"), "preparation_drafts", ["project_id"], unique=False
    )
    op.create_table(
        "preparation_plans",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("program_revision", sa.Integer(), nullable=False),
        sa.Column("settings_revision", sa.Integer(), nullable=False),
        sa.Column("phases", sa.JSON(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_preparation_plans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_preparation_plans")),
    )
    op.create_table(
        "preparation_queues",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("study_date", sa.Date(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("topic_position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_preparation_queues_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "study_date", name=op.f("pk_preparation_queues")),
    )
    op.create_table(
        "preparation_settings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_preparation_settings_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_preparation_settings")),
    )
    op.create_table(
        "preparation_versions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("undone", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_preparation_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "revision", name=op.f("pk_preparation_versions")),
    )
    op.create_table(
        "preparation_coach",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("study_date", sa.Date(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("automatic_attempted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["background_jobs.id"],
            name=op.f("fk_preparation_coach_job_id_background_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_preparation_coach_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "study_date", name=op.f("pk_preparation_coach")),
        sa.UniqueConstraint(
            "project_id", "study_date", name=op.f("uq_preparation_coach_project_id")
        ),
    )
    op.create_table(
        "preparation_reviews",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("easiness", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("due", sa.Date(), nullable=True),
        sa.Column("last_at", sa.DateTime(), nullable=True),
        sa.Column("successful_count", sa.Integer(), nullable=False),
        sa.Column("delayed_successes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["program_nodes.id"],
            name=op.f("fk_preparation_reviews_node_id_program_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_preparation_reviews_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "node_id", name=op.f("pk_preparation_reviews")),
    )
    op.create_table(
        "study_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("path", sa.JSON(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("seconds", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("understood", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["program_nodes.id"],
            name=op.f("fk_study_activities_node_id_program_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_study_activities_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_activities")),
    )
    op.create_index(
        op.f("ix_study_activities_project_id"), "study_activities", ["project_id"], unique=False
    )
    op.create_table(
        "study_intervals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["program_nodes.id"],
            name=op.f("fk_study_intervals_node_id_program_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_study_intervals_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_intervals")),
    )
    op.create_index(
        "ix_study_intervals_project_time",
        "study_intervals",
        ["project_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_intervals_session_id"), "study_intervals", ["session_id"], unique=False
    )
    op.create_table(
        "preparation_qualities",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("quality", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_preparation_qualities_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_preparation_qualities")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("preparation_qualities")
    op.drop_table("study_intervals")
    op.drop_table("study_activities")
    op.drop_table("preparation_reviews")
    op.drop_table("preparation_coach")
    op.drop_table("preparation_versions")
    op.drop_table("preparation_settings")
    op.drop_table("preparation_queues")
    op.drop_table("preparation_plans")
    op.drop_table("preparation_drafts")
    op.drop_column("attempts", "active_seconds")
    op.drop_column("attempts", "answer_mode")
    # ### end Alembic commands ###
