"""И2: аддитивный слой данных прохода 2; прежние связи остаются unknown."""

import sqlalchemy as sa
from alembic import op

revision = "20260918_0049"
down_revision = "20260915_0048"
branch_labels = None
depends_on = None

OLD_KINDS = (
    "parse",
    "typst_compile",
    "ai_grouping",
    "ai_import_repair",
    "ai_preparation",
    "ai_cleanup",
    "link_answers",
    "ai_answer_sections",
    "ai_program_build",
)


def _kind(values):
    return sa.Enum(*values, name="background_job_kind", native_enum=False, create_constraint=True)


def upgrade():
    op.add_column(
        "projects", sa.Column("coverage_revision", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("goal_passports", sa.Column("tree_detail", sa.String(), nullable=True))
    for name, kind in (
        ("roles", sa.JSON()),
        ("semantic_kind", sa.String()),
        ("evidence_ref", sa.JSON()),
        ("semantic_revision", sa.Integer()),
    ):
        op.add_column("bindings", sa.Column(name, kind, nullable=True))
    op.execute("UPDATE bindings SET semantic_kind = 'unknown'")
    with op.batch_alter_table("background_jobs") as batch:
        batch.alter_column(
            "kind",
            existing_type=_kind(OLD_KINDS),
            type_=_kind((*OLD_KINDS, "coverage_research")),
            existing_nullable=False,
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coverage_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("request_key", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("protocol_version", sa.String(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("fingerprints", sa.JSON(), nullable=False),
        sa.Column("model_roles", sa.JSON(), nullable=False),
        sa.Column("limits", sa.JSON(), nullable=False),
        sa.Column("execution_generation", sa.Integer(), nullable=False),
        sa.Column("stop_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "execution_generation >= 0", name=op.f("ck_coverage_runs_generation_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["background_jobs.id"],
            name=op.f("fk_coverage_runs_job_id_background_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_coverage_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_runs")),
        sa.UniqueConstraint("job_id", name=op.f("uq_coverage_runs_job_id")),
        sa.UniqueConstraint("project_id", "request_key", name=op.f("uq_coverage_runs_project_id")),
    )
    op.create_index(
        "ix_coverage_runs_project_created",
        "coverage_runs",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "coverage_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("task_key", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("targets", sa.JSON(), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("call_receipts", sa.JSON(), nullable=False),
        sa.Column("stop_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["coverage_tasks.id"],
            name=op.f("fk_coverage_tasks_parent_id_coverage_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["coverage_runs.id"],
            name=op.f("fk_coverage_tasks_run_id_coverage_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_tasks")),
        sa.UniqueConstraint("run_id", "task_key", name=op.f("uq_coverage_tasks_run_id")),
    )
    op.create_index(
        "ix_coverage_tasks_run_state", "coverage_tasks", ["run_id", "state"], unique=False
    )
    op.create_table(
        "coverage_block_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("material_revision", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("work_state", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("result_version", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("publication_state", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("reuse_ref", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["coverage_runs.id"],
            name=op.f("fk_coverage_block_results_run_id_coverage_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["coverage_tasks.id"],
            name=op.f("fk_coverage_block_results_task_id_coverage_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_block_results")),
        sa.UniqueConstraint("run_id", "block_id", name=op.f("uq_coverage_block_results_run_id")),
    )
    op.create_index(
        "ix_coverage_results_run_state",
        "coverage_block_results",
        ["run_id", "work_state"],
        unique=False,
    )
    op.create_index(
        "ix_coverage_results_material_revision",
        "coverage_block_results",
        ["material_id", "material_revision"],
        unique=False,
    )
    op.create_table(
        "coverage_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("proposal_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("feedback", sa.JSON(), nullable=True),
        sa.Column("applied_action_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["applied_action_id"],
            ["project_action_log.sequence"],
            name=op.f("fk_coverage_findings_applied_action_id_project_action_log"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_coverage_findings_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["coverage_runs.id"],
            name=op.f("fk_coverage_findings_run_id_coverage_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_findings")),
    )
    op.create_index(
        "ix_coverage_findings_project_state",
        "coverage_findings",
        ["project_id", "state"],
        unique=False,
    )
    op.create_table(
        "coverage_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("target_key", sa.String(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=True),
        sa.Column("anchor_fingerprint", sa.String(), nullable=True),
        sa.Column("goal_fingerprint", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("action_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["project_action_log.sequence"],
            name=op.f("fk_coverage_decisions_action_id_project_action_log"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_coverage_decisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_decisions")),
        sa.UniqueConstraint(
            "project_id", "kind", "target_key", name=op.f("uq_coverage_decisions_project_id")
        ),
    )
    op.create_index(
        "ix_coverage_decisions_project_kind",
        "coverage_decisions",
        ["project_id", "kind"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # Только на резервной копии/после экспорта; удаление результатов необратимо.
    for name in (
        "coverage_decisions",
        "coverage_findings",
        "coverage_block_results",
        "coverage_tasks",
        "coverage_runs",
    ):
        op.drop_table(name)
    op.execute("DELETE FROM background_jobs WHERE kind = 'coverage_research'")
    with op.batch_alter_table("background_jobs") as batch:
        batch.alter_column(
            "kind",
            existing_type=_kind((*OLD_KINDS, "coverage_research")),
            type_=_kind(OLD_KINDS),
            existing_nullable=False,
        )
    for name in ("roles", "semantic_kind", "evidence_ref", "semantic_revision"):
        op.drop_column("bindings", name)
    op.drop_column("goal_passports", "tree_detail")
    op.drop_column("projects", "coverage_revision")
