import { ArrowLeft, ChevronDown, ChevronRight, FilePlus2, GraduationCap, MoreHorizontal, Search, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, Navigate, useNavigate, useParams, useSearchParams } from "react-router";
import { CostEstimate, OfflineNotice } from "../../components/domain";
import { Button, Checkbox, ConfirmDialog, Dialog, EmptyState, Field, Menu, StatusBadge } from "../../components/ui";
import type { WorkspaceNode } from "../workspaceDemo";
import { resolveWorkspaceProject } from "../workspaceDemo";
import { LessonDocument } from "./LessonDocument";
import { createManualLesson, LESSON_DEMOS, lessonCountsForNode, lessonsForTopic } from "./lessonsDemo";
import type { LessonBlockDemo, LessonDemo } from "./lessonsDemo";

type BatchAction = "manual" | "ai" | "skip";
type SavedState = { expanded: string[]; checked: string[]; inspectorOpen: boolean; drafts: LessonDemo[] };
const flatten = (nodes: WorkspaceNode[]): WorkspaceNode[] => nodes.flatMap((node) => [node, ...flatten(node.children ?? [])]);
const findNode = (nodes: WorkspaceNode[], id: string) => flatten(nodes).find((node) => node.id === id);
const studyNodes = (node: WorkspaceNode) => flatten(node.children ?? []).filter((child) => child.type !== "section");
const labelCount = (draft: number, ready: number) => draft ? `${draft} черновик${draft === 1 ? "" : "а"}` : ready === 0 ? "нет урока" : ready === 1 ? "1 урок" : `${ready} урока`;

function cloneDemo(topicId: string, topicTitle: string, projectId: string): LessonDemo {
  const demo = LESSON_DEMOS[0];
  return { ...structuredClone(demo), id: crypto.randomUUID(), projectId, topicIds: [topicId], title: `Черновик: ${topicTitle}`, status: "draft", authorship: "model", requiresReview: false };
}

function findBlock(lesson: LessonDemo, id: string) {
  for (const section of lesson.document.sections) for (const row of section.rows) {
    const block = row.blocks.find((item) => item.id === id); if (block) return { row, block };
  }
  return undefined;
}

export function Lessons() {
  const { projectId = "demo" } = useParams(); const project = resolveWorkspaceProject(projectId); const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const storageKey = `tentex:lessons:${project.id}`;
  const stored = useMemo(() => { try { return JSON.parse(localStorage.getItem(storageKey) ?? "null") as SavedState | null; } catch { return null; } }, [storageKey]);
  const [selectedNodeId, setSelectedNodeId] = useState(params.get("topic") ?? project.nodes[0]?.id ?? "");
  const [expanded, setExpanded] = useState<string[]>(stored?.expanded ?? project.nodes.filter((node) => node.type === "section").map((node) => node.id));
  const [checked, setChecked] = useState<string[]>(stored?.checked ?? []); const [drafts, setDrafts] = useState<LessonDemo[]>(stored?.drafts ?? []);
  const [query, setQuery] = useState(""); const [selectedLessonId, setSelectedLessonId] = useState(params.get("lesson") ?? ""); const [selectedBlockId, setSelectedBlockId] = useState<string | null>(null);
  const [inspectorOpen, setInspectorOpen] = useState(stored?.inspectorOpen ?? true); const [deleteBlockId, setDeleteBlockId] = useState<string | null>(null); const [aiStep, setAiStep] = useState<"configure" | "storyboard">("configure"); const [aiOpen, setAiOpen] = useState(false); const [message, setMessage] = useState("");
  const [actions, setActions] = useState<Record<string, BatchAction>>({}); const [durations, setDurations] = useState<Record<string, number>>({});
  const allLessons = [...new Map([...LESSON_DEMOS, ...drafts].map((lesson) => [lesson.id, lesson])).values()]; const allNodes = useMemo(() => flatten(project.nodes), [project.nodes]); const selectedNode = findNode(project.nodes, selectedNodeId) ?? project.nodes[0];
  const topics = allNodes.filter((node) => node.type !== "section"); const selectedTopics = topics.filter((node) => checked.includes(node.id)); const mode = selectedTopics.length >= 2 ? "batch" : selectedNode.type === "section" ? "section" : "single";
  const topicLessons = selectedNode ? lessonsForTopic(selectedNode.id, allLessons) : []; const selectedLesson = topicLessons.find((lesson) => lesson.id === selectedLessonId) ?? topicLessons[0];

  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify({ expanded, checked, inspectorOpen, drafts })); }, [checked, drafts, expanded, inspectorOpen, storageKey]);
  useEffect(() => { const next = new URLSearchParams(); if (selectedNodeId) next.set("topic", selectedNodeId); if (selectedLesson) next.set("lesson", selectedLesson.id); setParams(next, { replace: true }); }, [selectedLesson?.id, selectedNodeId, setParams]);
  if (!project.lessonsEnabled) return <Navigate to={`/projects/${project.id}`} replace />;

  function selectNode(node: WorkspaceNode) { setSelectedNodeId(node.id); if (node.type !== "section") setChecked((current) => current.filter((id) => id !== node.id)); }
  function toggleChecked(id: string, include: string[]) { setChecked((current) => current.includes(id) ? current.filter((item) => !include.includes(item)) : [...new Set([...current, ...include])]); }
  function createManual(topic: WorkspaceNode) { const draft = createManualLesson(project.id, topic.id, topic.title); setDrafts((current) => [...current, draft]); setChecked([]); setSelectedNodeId(topic.id); setSelectedLessonId(draft.id); setMessage("Черновик создан локально"); }
  function createAi(topic: WorkspaceNode) { const draft = cloneDemo(topic.id, topic.title, project.id); setDrafts((current) => [...current, draft]); setChecked([]); setSelectedNodeId(topic.id); setSelectedLessonId(draft.id); setAiOpen(false); setMessage("Прототип: модель не вызывалась"); }
  function updateLesson(change: (lesson: LessonDemo) => LessonDemo) { if (!selectedLesson) return; setDrafts((current) => current.some((lesson) => lesson.id === selectedLesson.id) ? current.map((lesson) => lesson.id === selectedLesson.id ? change(lesson) : lesson) : [...current, change(structuredClone(selectedLesson))]); }
  function changeBlock(order: "up" | "down" | "duplicate" | "delete") {
    if (!selectedLesson || !selectedBlockId) return; updateLesson((lesson) => { const copy = structuredClone(lesson); const found = findBlock(copy, selectedBlockId); if (!found) return lesson; const index = found.row.blocks.findIndex((block) => block.id === selectedBlockId);
      if (order === "delete") found.row.blocks.splice(index, 1); else if (order === "duplicate") found.row.blocks.splice(index + 1, 0, { ...found.block, id: crypto.randomUUID() } as LessonBlockDemo); else { const target = index + (order === "up" ? -1 : 1); if (target >= 0 && target < found.row.blocks.length) [found.row.blocks[index], found.row.blocks[target]] = [found.row.blocks[target], found.row.blocks[index]]; } return copy; });
    if (order === "delete") setSelectedBlockId(null);
  }
  function addBlock(type: LessonBlockDemo["type"]) { if (!selectedLesson) return; const id = crypto.randomUUID(); const block: LessonBlockDemo = type === "rich-text" ? { id, type, paragraphs: ["Новая мысль урока."], sourceRefs: [] } : type === "callout" ? { id, type, tone: "neutral", title: "Определение", body: "Короткое определение для темы.", sourceRefs: [] } : type === "image" ? { id, type, alt: "Новый образ для урока", caption: "Подпись изображения.", assetState: "available", sourceRefs: [] } : type === "diagram" ? { id, type, title: "Схема", preview: "шаг 1 → шаг 2 → вывод", alt: "Схема процесса", sourceRefs: [] } : { id, type, activityId: id, dialect: "SQLite", prompt: "Сформулируйте SQL-задачу.", sourceRefs: [] };
    updateLesson((lesson) => { const copy = structuredClone(lesson); const row = copy.document.sections[0].rows.at(-1)!; if (type === "sql-activity") copy.document.sections[0].rows.push({ id: crypto.randomUUID(), preset: "full-width-practice", blocks: [block] }); else row.blocks.push(block); return copy; }); setSelectedBlockId(id);
  }
  function prepareBatch() { selectedTopics.forEach((topic) => { if (lessonsForTopic(topic.id, allLessons).length || actions[topic.id] === "skip") return; if (actions[topic.id] === "ai") createAi(topic); else createManual(topic); }); }
  function selectEmpty(scope: WorkspaceNode[]) { setChecked(scope.filter((node) => lessonsForTopic(node.id, allLessons).length === 0).map((node) => node.id)); }
  function renderTree(nodes: WorkspaceNode[]) { const normalized = query.trim().toLocaleLowerCase("ru"); return nodes.map((node) => { const children = node.children ?? []; const descendants = studyNodes(node); const ownLessons = lessonsForTopic(node.id, allLessons); const matches = !normalized || node.title.toLocaleLowerCase("ru").includes(normalized) || ownLessons.some((lesson) => lesson.title.toLocaleLowerCase("ru").includes(normalized)); const childContent = renderTree(children); if (!matches && childContent.every((item) => item === null)) return null; const open = normalized !== "" || expanded.includes(node.id); const counts = lessonCountsForNode(node, allLessons); const isSection = node.type === "section";
    return <div className="lessons-tree-node" key={node.id}>{isSection ? <div className={`lessons-tree-row ${selectedNodeId === node.id ? "is-selected" : ""}`}><button type="button" className="lessons-tree-chevron" onClick={() => setExpanded((current) => current.includes(node.id) ? current.filter((id) => id !== node.id) : [...current, node.id])} aria-label="Раскрыть раздел">{open ? <ChevronDown size={15} /> : <ChevronRight size={15} />}</button><Checkbox label="" checked={descendants.length > 0 && descendants.every((item) => checked.includes(item.id))} onCheckedChange={() => toggleChecked(node.id, descendants.map((item) => item.id))} /><button type="button" onClick={() => selectNode(node)}>{node.number}. {node.title}</button><small>{labelCount(counts.draft, counts.ready)}</small></div> : <div className={`lessons-tree-row is-topic ${selectedNodeId === node.id ? "is-selected" : ""}`}><span /><Checkbox label="" checked={checked.includes(node.id)} onCheckedChange={() => toggleChecked(node.id, [node.id])} /><button type="button" onClick={() => selectNode(node)}>{node.number}. {node.title}</button><small>{labelCount(counts.draft, counts.ready)}</small></div>}{isSection && open && <div className="lessons-tree-children">{childContent}</div>}</div>;
  }); }
  const block = selectedLesson && selectedBlockId ? findBlock(selectedLesson, selectedBlockId)?.block : undefined;
  return <div className="lessons-screen">
    <aside className="lessons-tree"><header><Link to={`/projects/${project.id}`} aria-label="К рабочей области"><ArrowLeft size={16} /></Link><strong>{project.name}</strong></header><label className="lessons-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Найти тему или урок" /></label><nav>{renderTree(project.nodes)}</nav><footer><Link to={`/projects/${project.id}/program?mode=textbook`}>Программа</Link><Link className="is-active" to={`/projects/${project.id}/lessons`}>Уроки <small>3</small></Link><button disabled>Карточки</button></footer></aside>
    <main className="lessons-main">{message && <p className="lessons-message" role="status">{message}</p>}
      {mode === "section" && <section className="lessons-overview"><p>Раздел программы</p><h1>{selectedNode.title}</h1><p>{selectedNode.purpose ?? "Выберите тему в дереве или подготовьте уроки для раздела."}</p><div><Button onClick={() => selectEmpty(studyNodes(selectedNode))}>Выбрать темы без уроков</Button><Button variant="secondary" onClick={() => selectEmpty(topics)}>Создавать по порядку</Button></div></section>}
      {mode === "batch" && <section className="lessons-batch"><header><div><p>Массовое создание</p><h1>{selectedTopics.length} темы</h1></div><Button onClick={prepareBatch}>Подготовить черновики</Button></header><div className="lessons-batch-table">{selectedTopics.map((topic, index) => { const entries = lessonsForTopic(topic.id, allLessons); const created = entries.find((lesson) => lesson.status === "draft"); return <div key={topic.id}><span>{index + 1}</span><strong>{topic.title}</strong><small>{topic.sources.length ? "есть материал" : "нет материала"} · {entries.length ? `${entries.length} урок` : "нет урока"}</small>{created ? <button type="button" onClick={() => { setChecked([]); setSelectedNodeId(topic.id); setSelectedLessonId(created.id); }}>Черновик готов</button> : <><select value={actions[topic.id] ?? "manual"} onChange={(event) => setActions((current) => ({ ...current, [topic.id]: event.target.value as BatchAction }))}><option value="manual">вручную</option><option value="ai">с ИИ</option><option value="skip">пропустить</option></select><input type="number" min="5" value={durations[topic.id] ?? 15} onChange={(event) => setDurations((current) => ({ ...current, [topic.id]: Number(event.target.value) }))} /></>}</div>; })}</div></section>}
      {mode === "single" && <section className="lessons-single">{!selectedLesson ? <EmptyState title="Для этой темы ещё нет урока" icon={<GraduationCap size={28} />}><p>Создайте черновик вручную или соберите его по storyboard.</p><div><Button onClick={() => createManual(selectedNode)}>Создать вручную</Button><Button variant="secondary" onClick={() => { setAiStep("configure"); setAiOpen(true); }}>Собрать с ИИ</Button></div></EmptyState> : <><header className="lessons-editor-head"><div><p>{selectedNode.title} · {selectedNode.sources.length ? "источники доступны" : "источников пока нет"}</p><select value={selectedLesson.id} onChange={(event) => setSelectedLessonId(event.target.value)}>{topicLessons.map((lesson) => <option key={lesson.id} value={lesson.id}>{lesson.title}</option>)}</select></div><div><StatusBadge tone={selectedLesson.status === "draft" ? "warning" : "success"}>{selectedLesson.status === "draft" ? "Черновик" : "Готов"}</StatusBadge><span>Сохранено</span><Button variant="secondary" onClick={() => navigate(`/projects/${project.id}?topic=${selectedNode.id}&tab=lesson&lesson=${selectedLesson.id}`)}>Открыть в Рабочей области</Button><Button onClick={() => updateLesson((lesson) => ({ ...lesson, status: "ready" }))}>Готов</Button></div></header><div className="lessons-editor-fields"><Field label="Название"><input value={selectedLesson.title} onChange={(event) => updateLesson((lesson) => ({ ...lesson, title: event.target.value }))} /></Field><Field label="Цель"><input value={selectedLesson.goal} onChange={(event) => updateLesson((lesson) => ({ ...lesson, goal: event.target.value }))} /></Field><Menu label="Добавить блок" trigger={<Button variant="secondary"><FilePlus2 size={15} />Добавить блок</Button>} items={[{ label: "Текст", onSelect: () => addBlock("rich-text") }, { label: "Определение", onSelect: () => addBlock("callout") }, { label: "Изображение", onSelect: () => addBlock("image") }, { label: "Диаграмма", onSelect: () => addBlock("diagram") }, { label: "SQL-задача", onSelect: () => addBlock("sql-activity") }]} /></div>{selectedBlockId && <div className="lessons-block-actions"><Button variant="ghost" onClick={() => changeBlock("up")}>Вверх</Button><Button variant="ghost" onClick={() => changeBlock("down")}>Вниз</Button><Button variant="ghost" onClick={() => changeBlock("duplicate")}>Дублировать</Button><Button variant="ghost" onClick={() => setDeleteBlockId(selectedBlockId)}>Удалить</Button></div>}<LessonDocument document={selectedLesson.document} mode="editor" selectedBlockId={selectedBlockId} onSelectBlock={setSelectedBlockId} /></>}</section>}
    </main>
    {inspectorOpen && <aside className="lessons-inspector"><button type="button" onClick={() => setInspectorOpen(false)}>Скрыть inspector</button>{block ? <><h2>Блок</h2><p>Тип: {block.type}</p><label>Layout preset<select defaultValue="flow"><option>flow</option><option>media-left</option><option>media-right</option><option>two-equal</option><option>wide</option><option>full-width-practice</option></select></label><p>Источники: {block.sourceRefs.length || "нет"}</p><Button disabled>Объяснить проще</Button><Button disabled>Добавить пример</Button><Button disabled>Сделать короче</Button></> : <p>Выберите блок документа.</p>}</aside>}
    {!inspectorOpen && <button type="button" className="lessons-open-inspector" onClick={() => setInspectorOpen(true)}><MoreHorizontal size={16} />Inspector</button>}
    <ConfirmDialog open={Boolean(deleteBlockId)} onOpenChange={(open) => !open && setDeleteBlockId(null)} title="Удалить блок?" confirmLabel="Удалить блок" destructive onConfirm={() => changeBlock("delete")}><p>Блок исчезнет из локального черновика.</p></ConfirmDialog>
    <Dialog open={aiOpen} onOpenChange={setAiOpen} title={aiStep === "configure" ? "Собрать урок с ИИ" : "Storyboard урока"} description="Это mock-сценарий: модель не вызывается." footer={<><Button variant="ghost" onClick={() => setAiOpen(false)}>Отменить</Button>{aiStep === "configure" ? <Button onClick={() => setAiStep("storyboard")}>Дальше</Button> : <Button disabled={!project.modelsEnabled} onClick={() => createAi(selectedNode)}><Sparkles size={15} />Собрать черновик</Button>}</>}>
      {!project.modelsEnabled && <OfflineNotice reason="disabled" alternative="Создайте урок вручную — это работает офлайн." />}
      {aiStep === "configure" ? <div className="lessons-ai-form"><p>Темы: {selectedTopics.length ? selectedTopics.map((topic) => topic.title).join(", ") : selectedNode.title}</p><Field label="Цель"><input defaultValue="Объяснить и закрепить ключевое понятие" /></Field><Field label="Сложность"><select defaultValue="basic"><option>intro</option><option>basic</option><option>advanced</option></select></Field><Field label="Длительность"><input type="number" defaultValue="18" /></Field><Checkbox label="Активности" checked onCheckedChange={() => undefined} /><Checkbox label="Медиа" checked onCheckedChange={() => undefined} /><p>Основание: источники проекта / смешанное / знания модели</p></div> : <div className="lessons-storyboard"><p>1. Контекст · текст · flow</p><p>2. Основная идея · определение и изображение · media-left</p><p>3. Проверка · SQL-задача · full-width-practice</p><CostEstimate calls={3} cost={0.06} minutes={1} pricesFrom="05.08.2026" /></div>}
    </Dialog>
  </div>;
}
